FROM linuxserver/deluge

RUN mkdir -p /home/deluge \
    && mkdir -p /home/deluge/complete \
    && mkdir -p /home/deluge/incomplete \
    && mkdir -p /home/deluge/watch \
    && mkdir -p /home/deluge/torrentfiles

RUN chmod 777 -R /home/deluge